//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day05_HydrothermalVenture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day05_HydrothermalVenture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 299,462 -&gt; 299,747
        ///855,314 -&gt; 855,140
        ///981,328 -&gt; 798,328
        ///610,444 -&gt; 680,374
        ///797,242 -&gt; 606,242
        ///217,42 -&gt; 147,42
        ///735,378 -&gt; 735,188
        ///247,192 -&gt; 912,192
        ///377,341 -&gt; 768,341
        ///472,701 -&gt; 66,701
        ///48,970 -&gt; 885,133
        ///893,35 -&gt; 664,35
        ///617,237 -&gt; 951,237
        ///540,643 -&gt; 190,293
        ///575,815 -&gt; 302,815
        ///146,380 -&gt; 146,562
        ///568,481 -&gt; 568,161
        ///38,101 -&gt; 921,984
        ///613,12 -&gt; 185,12
        ///967,30 -&gt; 17,980
        ///823,620 -&gt; 584,859
        ///672,822 -&gt; 413,822
        ///259,626 -&gt; 385,752
        ///752,415 -&gt; 857,310
        ///758,659 -&gt; 758,76
        ///909,893 -&gt; 35,19
        ///964,91 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CloudLines {
            get {
                return ResourceManager.GetString("CloudLines", resourceCulture);
            }
        }
    }
}
