//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day01_SonarSweep.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day01_SonarSweep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 191
        ///185
        ///188
        ///189
        ///204
        ///213
        ///215
        ///227
        ///222
        ///221
        ///236
        ///235
        ///236
        ///232
        ///224
        ///228
        ///234
        ///226
        ///227
        ///228
        ///230
        ///232
        ///234
        ///213
        ///197
        ///198
        ///210
        ///238
        ///248
        ///261
        ///263
        ///265
        ///262
        ///295
        ///296
        ///311
        ///330
        ///333
        ///337
        ///344
        ///345
        ///356
        ///359
        ///360
        ///364
        ///367
        ///383
        ///386
        ///387
        ///391
        ///424
        ///426
        ///428
        ///440
        ///442
        ///446
        ///450
        ///423
        ///428
        ///423
        ///425
        ///445
        ///429
        ///436
        ///465
        ///456
        ///463
        ///461
        ///463
        ///483
        ///484
        ///500
        ///517
        ///525
        ///529
        ///527
        ///530
        ///535
        ///566
        ///578
        ///582
        ///587
        ///604
        ///613
        ///614
        ///609
        ///611
        ///619
        ///623
        ///627
        ///621
        ///622
        ///626
        ///644
        ///646
        ///655
        ///657
        ///659
        ///661
        ///671
        ///673
        ///668
        ///67 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DepthMeasurements {
            get {
                return ResourceManager.GetString("DepthMeasurements", resourceCulture);
            }
        }
    }
}
